#!/usr/bin/env python3
"""Build Lucky Cat HSK game data from the product by-level CSVs.

Reads  product/by-level/HSK<n>_words-to-remember_bilingual.csv  (n = 1..6)
Writes game/data/words.js      (window.HSK_DATA = {...}; loadable from file://)
       game/data/words.json    (same payload, pure JSON)
       game/data/manifest.json (per-level counts / coverage summary)

Re-run whenever the vocabulary is refreshed. Safe to re-run any time.

Per-word record (minified, see game plan section 5):
  h  hanzi            p  pinyin          e  english         t  thai ("" if missing)
  lv level            f  frequency       ta tests_appeared  tt tests_total
  c  tier: 1=Core, 0=Extended           n  1 = introduced at this level, 0 = recycled
"""

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "product" / "by-level"
OUT_DIR = Path(__file__).resolve().parent / "data"
# Optional Thai supplement (AI-generated glosses for words the curated data
# doesn't cover yet). Only consulted when a row's thai column is empty.
SUPPLEMENT = ROOT / "product" / "thai-supplement.csv"

LEVELS = range(1, 7)

# Fixes for rows whose source gloss is broken (english = the hanzi itself).
# Keyed by hanzi; applied on top of the CSVs, which are generated files.
OVERRIDES = {
    "廖": {"e": "Liao (a surname)", "t": "เหลียว (แซ่)"},
    "萄": {"e": "grape (as in 葡萄)", "t": "องุ่น (ใน 葡萄)"},
    "蔡": {"e": "Cai (a surname)", "t": "ไช่ (แซ่)"},
}


def load_supplement() -> dict:
    if not SUPPLEMENT.exists():
        return {}
    with open(SUPPLEMENT, encoding="utf-8-sig", newline="") as fh:
        return {r["hanzi"].strip(): r["thai"].strip()
                for r in csv.DictReader(fh) if r["thai"].strip()}


def read_level(level: int, supplement: dict) -> list[dict]:
    path = SRC_DIR / f"HSK{level}_words-to-remember_bilingual.csv"
    words = []
    with open(path, encoding="utf-8-sig", newline="") as fh:
        for row in csv.DictReader(fh):
            hanzi = row["hanzi"].strip()
            if not hanzi:
                continue
            fix = OVERRIDES.get(hanzi, {})
            row["english"] = fix.get("e", row["english"])
            if not row["thai"].strip():
                row["thai"] = fix.get("t") or supplement.get(hanzi, "")
            words.append({
                "h": hanzi,
                "p": row["pinyin"].strip(),
                "e": row["english"].strip(),
                "t": row["thai"].strip(),
                "lv": level,
                "f": int(float(row["freq"] or 0)),
                "ta": int(float(row["tests_appeared"] or 0)),
                "tt": int(float(row["tests_total"] or 0)),
                "c": 1 if row["tier"].strip().lower() == "core" else 0,
                "n": 1 if row["status"].strip().lower().startswith("new") else 0,
            })
    # keep the CSV's frequency ranking (already sorted by rank, but be safe)
    words.sort(key=lambda w: -w["f"])
    return words


def main() -> int:
    missing = [n for n in LEVELS
               if not (SRC_DIR / f"HSK{n}_words-to-remember_bilingual.csv").exists()]
    if missing:
        print(f"ERROR: missing by-level CSVs for HSK {missing} in {SRC_DIR}")
        return 1

    supplement = load_supplement()
    if supplement:
        print(f"thai supplement: {len(supplement)} words loaded from {SUPPLEMENT.name}")
    levels = {str(n): read_level(n, supplement) for n in LEVELS}

    manifest = {"tests_total": {}, "levels": {}}
    for n in LEVELS:
        ws = levels[str(n)]
        manifest["levels"][str(n)] = {
            "words": len(ws),
            "core": sum(w["c"] for w in ws),
            "new": sum(w["n"] for w in ws),
            "thai": sum(1 for w in ws if w["t"]),
            "freq_total": sum(w["f"] for w in ws),
        }
        manifest["tests_total"][str(n)] = ws[0]["tt"] if ws else 0

    payload = {"manifest": manifest, "levels": levels}

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    js_blob = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    (OUT_DIR / "words.js").write_text(
        "// Generated by build_game_data.py - do not edit; rebuild from product/by-level CSVs.\n"
        f"window.HSK_DATA={js_blob};\n",
        encoding="utf-8")
    (OUT_DIR / "words.json").write_text(js_blob, encoding="utf-8")
    (OUT_DIR / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    total = sum(m["words"] for m in manifest["levels"].values())
    print(f"OK: {total} word rows across HSK1-6 -> {OUT_DIR}")
    for n in LEVELS:
        m = manifest["levels"][str(n)]
        print(f"  HSK{n}: {m['words']:>5} words | core {m['core']:>5} | "
              f"new {m['new']:>5} | thai {m['thai']:>5}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
