#!/usr/bin/env python3
"""Build flashcard example-sentence data from data/examples.csv.

Reads  data/examples.csv  (curated: AI-generated + verified rows, hanzi,sentence,en)
Writes data/examples.js   (window.HSK_EXAMPLES = {...}; loadable from file://)
       data/examples.json  (same payload, pure JSON — tests/validation)

These are the flashcard-back "In a sentence" examples for words that have NO
cloze entry (cloze words already provide their own sentence via data/cloze.js;
main.js merges the two). English-only by design for now: Thai translations go
through the native-review pipeline in a later pass, so no `th` field is emitted
here and the flashcard falls back to English for Thai users (see
src/examples.js: exampleFor).

Refuses to emit anything if any row fails validation (target hanzi present,
length bounds, terminal punctuation, no duplicate/overlap with cloze). Safe to
re-run any time. Deterministic CSV -> JS; never calls any network/AI service.
"""
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "data" / "examples.csv"
CLOZE = ROOT / "data" / "cloze.json"
END_PUNCT = ("。", "？", "！")


def row_errors(hanzi, sentence, en, cloze_keys):
    errs = []
    if not hanzi:
        return ["empty hanzi"]
    if hanzi in cloze_keys:
        errs.append(f"{hanzi}: already has a cloze sentence (belongs in cloze.csv, not here)")
    if hanzi not in sentence:
        errs.append(f"{hanzi}: target hanzi not present in sentence {sentence!r}")
    if not sentence or sentence[-1] not in END_PUNCT:
        errs.append(f"{hanzi}: sentence must end with one of 。？！ -> {sentence!r}")
    body = sentence[:-1] if sentence and sentence[-1] in END_PUNCT else sentence
    if not (5 <= len(body) <= 16):
        errs.append(f"{hanzi}: sentence body length {len(body)} outside 5..16 -> {sentence!r}")
    if not en:
        errs.append(f"{hanzi}: empty english translation")
    return errs


def main():
    cloze_keys = set(json.loads(CLOZE.read_text(encoding="utf-8"))) if CLOZE.exists() else set()
    payload, errors, dupes = {}, [], []
    with open(SRC, encoding="utf-8-sig", newline="") as fh:
        for row in csv.DictReader(fh):
            h = row["hanzi"].strip()
            s = row["sentence"].strip()
            en = row["en"].strip()
            errors.extend(row_errors(h, s, en, cloze_keys))
            if h in payload:
                dupes.append(h)
            payload[h] = {"s": s, "en": en}
    if dupes:
        errors.append(f"duplicate hanzi rows: {dupes}")
    if errors:
        print(f"{len(errors)} error(s):", file=sys.stderr)
        for e in errors:
            print("  " + e, file=sys.stderr)
        sys.exit(1)

    payload = dict(sorted(payload.items()))
    js = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    (ROOT / "data" / "examples.json").write_text(js + "\n", encoding="utf-8")
    (ROOT / "data" / "examples.js").write_text(
        "// Generated by build_examples_data.py - do not edit; "
        "rebuild from data/examples.csv.\n"
        f"window.HSK_EXAMPLES={js};\n", encoding="utf-8")
    print(f"{len(payload)} example sentences -> data/examples.js ({len(js)//1024} KB)")


if __name__ == "__main__":
    main()
