#!/usr/bin/env python3
"""Build cloze data from data/cloze-sentences.csv.

Reads  data/cloze-sentences.csv  (curated: mined tatoeba + AI rows, reviewed)
Writes data/cloze.js    (window.HSK_CLOZE = {...}; loadable from file://)
       data/cloze.json  (same payload, pure JSON — tests/validation)

Refuses to emit anything if any row fails clozelib.row_errors (content
quality: exactly-one target, 4-14 hanzi, level-capped vocab, vetted
distractor constraints). Safe to re-run any time.
"""
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "scripts" / "cloze"))
from clozelib import load_levels, row_errors  # noqa: E402

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "data" / "cloze-sentences.csv"


def main():
    levels = load_levels(ROOT / "data" / "words.json")
    payload, errors, dupes = {}, [], []
    with open(SRC, encoding="utf-8-sig", newline="") as fh:
        for row in csv.DictReader(fh):
            errors.extend(row_errors(row, levels))
            h = row["hanzi"].strip()
            if h in payload:
                dupes.append(h)
            payload[h] = {"s": row["sentence"].strip(), "en": row["en"].strip(),
                          "th": row["th"].strip(),
                          "d": [row["d1"].strip(), row["d2"].strip(), row["d3"].strip()]}
    if dupes:
        errors.append(f"duplicate hanzi rows: {dupes}")
    if errors:
        print(f"{len(errors)} error(s):", file=sys.stderr)
        for e in errors:
            print("  " + e, file=sys.stderr)
        sys.exit(1)

    payload = dict(sorted(payload.items()))
    js = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    (ROOT / "data" / "cloze.json").write_text(js + "\n", encoding="utf-8")
    (ROOT / "data" / "cloze.js").write_text(
        "// Generated by build_cloze_data.py - do not edit; "
        "rebuild from data/cloze-sentences.csv.\n"
        f"window.HSK_CLOZE={js};\n", encoding="utf-8")
    n12 = sum(1 for h, lv in levels.items() if lv <= 2)
    print(f"{len(payload)} sentences ({len(payload)}/{n12} HSK1-2 words covered) "
          f"-> data/cloze.js ({len(js)//1024} KB)")


if __name__ == "__main__":
    main()
